[build]
  publish = "dist"
  command = "npm run build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev:vite"
  port = 8888
  targetPort = 3000
  publish = "dist"
  functions = "functions"
